# Generated by Django 2.0 on 2020-06-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_personne2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personne2',
        ),
    ]
